name: iOS

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: List available Xcode versions
      run: ls /Applications | grep Xcode

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

    - name: Show current version of Xcode
      run: xcodebuild -version

    - name: Run Script
      run: npm run wdio
